### ISSUE TITLE
"fcsrv run" works, but "fcsrv start" does not work

### ISSUE THREAD

**Issue by hsea** [gngpp/fcsrv#16]
fcsrv run, 使用示例命令，可以返回正确结果{"solve":true,"objects":[3]}
sudo fcsrv start，使用示例命令，返回curl: (7) Failed to connect to 127.0.0.1 port 8000 after 0 ms: Couldn't connect to server
sudo fcsrv status，返回fcsrv is running with pid: 835990，应该是运行了

另外请问fcsrv start时参数如何设置？是直接跟在后面还是要配置文件呢？

**Comment by gngpp** [comment]
参数跟run一样，-h就出来了。fcsrv看启动日志

**Comment by hsea** [comment]
/etc/ninja$ uname -a
Linux DMIT-LAX2024 6.1.0-15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.66-1 (2023-12-09) x86_64 GNU/Linux

/etc/ninja$ sudo fcsrv restart
/etc/ninja$ sudo fcsrv log
STDERR>
Error: Permission denied (os error 13)

/etc/ninja$ fcsrv log
STDERR>
Error: Permission denied (os error 13)

似乎是权限问题。。

**Comment by gngpp** [comment]
在纯sudo用户里跑 因为你sudo运行 daemon这部操作在fork进程之后会丢弃sudo权限运行，有空我再修复

**Comment by gngpp** [comment]
你看看docker跑就没有这个事 默认纯root

**Comment by hsea** [comment]
> 你看看docker跑就没有这个事 默认纯root

切换到纯root确实可以了，第一次知道纯root的概念，学习了
