### ISSUE TITLE
fcsrv update提示No asset found for target: `x86_64-unknown-linux-gnu`

### ISSUE THREAD

**Issue by hsea** [gngpp/fcsrv#19]
fcsrv update好像有一点小bug，没法自动更新，手动更新没问题，不影响使用

:~$ sudo fcsrv update
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v0.1.5
Checking latest released version... v0.1.6
New release found! v0.1.5 --> v0.1.6
New release is compatible
Error: ReleaseError: No asset found for target: `x86_64-unknown-linux-gnu`

:~$ uname -a
Linux DMIT-2024 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux

:~$ sudo su -
:~# fcsrv update
Checking target-arch... x86_64-unknown-linux-gnu
Checking current version... v0.1.5
Checking latest released version... v0.1.6
New release found! v0.1.5 --> v0.1.6
New release is compatible
Error: ReleaseError: No asset found for target: `x86_64-unknown-linux-gnu`

**Comment by gngpp** [comment]
用docker就行了 因为编译太麻烦 我就没有发布到GitHub
