### ISSUE TITLE
关于-A参数

### ISSUE THREAD

**Issue by hggcgd** [gngpp/fcsrv#36]
用 fcsrv run -A sk-12345运行

curl --location 'http://127.0.0.1:8000/task' \
--header 'Content-Type: application/json' \
--data '{
    "game_variant_instructions": ["3d_rollball_objects", "Use the arrows to rotate the object to face in the direction of the hand"],
    "images": ["/9j/4A....."]
}'
会返回 {"error":"Invalid API key","solve":false,"objects":[]} 
如果用 fcsrv run
curl --location 'http://127.0.0.1:8000/task' \
--header 'Content-Type: application/json' \
--data '{
    "api_key": "sk-12345",
    "game_variant_instructions": ["3d_rollball_objects", "Use the arrows to rotate the object to face in the direction of the hand"],
    "images": ["/9j/4A....."]
}'
就能返回
{
    "solve": true,
    "objects": [
        3
    ]
}

**Comment by gngpp** [comment]
<img width="1601" alt="image" src="https://github.com/gngpp/fcsrv/assets/51810656/cf8b8373-d40b-4e12-b0e2-8c5cd4841302">
<img width="1956" alt="image" src="https://github.com/gngpp/fcsrv/assets/51810656/2fce0e27-7774-4ff8-b30c-17aa02963c80">
